# Generated by Django 4.0.5 on 2022-06-25 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0002_alter_user_options_alter_user_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='last_login_time',
            new_name='last_active_at',
        ),
    ]
