# Generated by Django 4.0.5 on 2022-06-25 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0003_rename_last_login_time_user_last_active_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='last_active_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='password_updated_at',
            field=models.DateTimeField(),
        ),
    ]
