# Generated by Django 4.0.5 on 2022-07-04 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0006_alter_user_last_active_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
