# Generated by Django 4.0.5 on 2022-07-04 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0007_alter_user_password_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[(1, 'MALE'), (2, 'FEMALE')], max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='present_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_experience',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_marks',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
    ]
