# Generated by Django 4.0.5 on 2022-06-25 07:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('exam', '0005_subjectcategory_subject_chaptercategory_chapter'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chapter',
            options={'ordering': ('sequence', 'created_at'), 'verbose_name': 'Chapter', 'verbose_name_plural': 'Chapters'},
        ),
        migrations.AlterModelOptions(
            name='chaptercategory',
            options={'ordering': ('sequence', 'created_at'), 'verbose_name': 'Chapter Category', 'verbose_name_plural': 'Chapter Categories'},
        ),
        migrations.AlterModelOptions(
            name='examtitle',
            options={'ordering': ('sequence', 'created_at'), 'verbose_name': 'Exam Title', 'verbose_name_plural': 'Exam Titles'},
        ),
        migrations.AlterModelOptions(
            name='subject',
            options={'ordering': ('sequence', 'created_at'), 'verbose_name': 'Subject', 'verbose_name_plural': 'Subjects'},
        ),
        migrations.AlterModelOptions(
            name='subjectcategory',
            options={'ordering': ('sequence', 'created_at'), 'verbose_name': 'Subject Category', 'verbose_name_plural': 'Subject Categories'},
        ),
        migrations.AlterField(
            model_name='chapter',
            name='chapter_position',
            field=models.PositiveIntegerField(blank=True, help_text='What is the position of this chapter.', null=True),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='created_by',
            field=models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='is_active',
            field=models.BooleanField(default=False, help_text='Toggles the global visibility of the record, if flase then it will be deleted for the user'),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='is_published',
            field=models.BooleanField(default=False, help_text='If false, it will be unavailable for end user!'),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='name',
            field=models.CharField(help_text='Name of the chapter. (Ex: বই পড়া)', max_length=150),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='sequence',
            field=models.PositiveBigIntegerField(default=0, help_text='Ordering Criteria.'),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='updated_by',
            field=models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(app_label)s_%(class)s_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='chaptercategory',
            name='created_by',
            field=models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='chaptercategory',
            name='is_active',
            field=models.BooleanField(default=False, help_text='Toggles the global visibility of the record, if flase then it will be deleted for the user'),
        ),
        migrations.AlterField(
            model_name='chaptercategory',
            name='is_published',
            field=models.BooleanField(default=False, help_text='If false, it will be unavailable for end user!'),
        ),
        migrations.AlterField(
            model_name='chaptercategory',
            name='name',
            field=models.CharField(help_text='Name of the subject category. (Ex: Goddo/Poddo/Uponnas/Natok)', max_length=50),
        ),
        migrations.AlterField(
            model_name='chaptercategory',
            name='number_of_question',
            field=models.PositiveIntegerField(blank=True, help_text='Total Number of question are stored in the databse under this catagory', null=True),
        ),
        migrations.AlterField(
            model_name='chaptercategory',
            name='sequence',
            field=models.PositiveBigIntegerField(default=0, help_text='Ordering Criteria.'),
        ),
        migrations.AlterField(
            model_name='chaptercategory',
            name='updated_by',
            field=models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(app_label)s_%(class)s_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='examtitle',
            name='created_by',
            field=models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='examtitle',
            name='is_active',
            field=models.BooleanField(default=False, help_text='Toggles the global visibility of the record, if flase then it will be deleted for the user'),
        ),
        migrations.AlterField(
            model_name='examtitle',
            name='is_published',
            field=models.BooleanField(default=False, help_text='If false, it will be unavailable for end user!'),
        ),
        migrations.AlterField(
            model_name='examtitle',
            name='name',
            field=models.CharField(help_text='Name of the topic. (Ex: SSC)', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='examtitle',
            name='sequence',
            field=models.PositiveBigIntegerField(default=0, help_text='Ordering Criteria.'),
        ),
        migrations.AlterField(
            model_name='examtitle',
            name='updated_by',
            field=models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(app_label)s_%(class)s_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='subject',
            name='created_by',
            field=models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='subject',
            name='is_active',
            field=models.BooleanField(default=False, help_text='Toggles the global visibility of the record, if flase then it will be deleted for the user'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='is_published',
            field=models.BooleanField(default=False, help_text='If false, it will be unavailable for end user!'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=models.CharField(help_text='Name of the subject. (Ex: Bangla First Paper)', max_length=150),
        ),
        migrations.AlterField(
            model_name='subject',
            name='sequence',
            field=models.PositiveBigIntegerField(default=0, help_text='Ordering Criteria.'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='updated_by',
            field=models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(app_label)s_%(class)s_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='subjectcategory',
            name='created_by',
            field=models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='subjectcategory',
            name='is_active',
            field=models.BooleanField(default=False, help_text='Toggles the global visibility of the record, if flase then it will be deleted for the user'),
        ),
        migrations.AlterField(
            model_name='subjectcategory',
            name='is_published',
            field=models.BooleanField(default=False, help_text='If false, it will be unavailable for end user!'),
        ),
        migrations.AlterField(
            model_name='subjectcategory',
            name='name',
            field=models.CharField(help_text='Name of the Subject Category. (Ex: Science/Arts/Commerce)', max_length=50),
        ),
        migrations.AlterField(
            model_name='subjectcategory',
            name='sequence',
            field=models.PositiveBigIntegerField(default=0, help_text='Ordering Criteria.'),
        ),
        migrations.AlterField(
            model_name='subjectcategory',
            name='updated_by',
            field=models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(app_label)s_%(class)s_updated_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterModelTable(
            name='chapter',
            table='chapter',
        ),
        migrations.AlterModelTable(
            name='chaptercategory',
            table='chapter_category',
        ),
        migrations.AlterModelTable(
            name='examtitle',
            table='exam_title',
        ),
        migrations.AlterModelTable(
            name='subject',
            table='subject',
        ),
        migrations.AlterModelTable(
            name='subjectcategory',
            table='subject_category',
        ),
        migrations.CreateModel(
            name='BoardYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveBigIntegerField(default=0, help_text='Ordering Criteria.')),
                ('is_published', models.BooleanField(default=False, help_text='If false, it will be unavailable for end user!')),
                ('is_active', models.BooleanField(default=False, help_text='Toggles the global visibility of the record, if flase then it will be deleted for the user')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('board_name', models.CharField(help_text='Name of the Board With year. (Ex: Rajshahi)', max_length=255)),
                ('year', models.CharField(blank=True, help_text='Year (Ex: 2018) ', max_length=4, null=True)),
                ('code', models.CharField(blank=True, help_text='Short Code of the Board. (Ex: Raj-18)', max_length=10, null=True)),
                ('created_by', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(app_label)s_%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Board',
                'verbose_name_plural': 'Boards',
                'db_table': 'board_year',
                'ordering': ('sequence', 'code', 'created_at'),
            },
        ),
    ]
