# Generated by Django 4.0.5 on 2022-06-25 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0006_alter_chapter_options_alter_chaptercategory_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='boardyear',
            options={'ordering': ('sequence', 'code', 'created_at'), 'verbose_name': 'Board', 'verbose_name_plural': '6. Boards'},
        ),
        migrations.AlterModelOptions(
            name='chapter',
            options={'ordering': ('sequence', 'created_at'), 'verbose_name': 'Chapter', 'verbose_name_plural': '5. Chapters'},
        ),
        migrations.AlterModelOptions(
            name='chaptercategory',
            options={'ordering': ('sequence', 'created_at'), 'verbose_name': 'Chapter Category', 'verbose_name_plural': '4. Chapter Categories'},
        ),
        migrations.AlterModelOptions(
            name='examtitle',
            options={'ordering': ('sequence', 'created_at'), 'verbose_name': 'Exam Title', 'verbose_name_plural': '1. Exam Titles'},
        ),
        migrations.AlterModelOptions(
            name='subject',
            options={'ordering': ('sequence', 'created_at'), 'verbose_name': 'Subject', 'verbose_name_plural': '3. Subjects'},
        ),
        migrations.AlterModelOptions(
            name='subjectcategory',
            options={'ordering': ('sequence', 'created_at'), 'verbose_name': 'Subject Category', 'verbose_name_plural': '2. Subject Categories'},
        ),
    ]
