# Generated by Django 4.0.5 on 2022-06-25 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0007_alter_boardyear_options_alter_chapter_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examtitle',
            name='expansion_of_name',
            field=models.CharField(blank=True, help_text='Expansion of the name, if any.  (Ex: Secondary School Certificate', max_length=150, null=True),
        ),
    ]
