# Generated by Django 4.0.5 on 2022-06-25 13:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('exam', '0009_alter_boardyear_updated_by_alter_chapter_updated_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveBigIntegerField(default=0, help_text='Ordering Criteria.')),
                ('is_published', models.BooleanField(default=False, help_text='If false, it will be unavailable for end user!')),
                ('is_active', models.BooleanField(default=False, help_text='Toggles the global visibility of the record, if flase then it will be deleted for the user')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('value', models.TextField()),
                ('created_by', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, db_index=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(app_label)s_%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Answers',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveBigIntegerField(default=0, help_text='Ordering Criteria.')),
                ('is_published', models.BooleanField(default=False, help_text='If false, it will be unavailable for end user!')),
                ('is_active', models.BooleanField(default=False, help_text='Toggles the global visibility of the record, if flase then it will be deleted for the user')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uddipok', models.TextField()),
                ('question', models.TextField()),
                ('image', models.ImageField(upload_to='question/images/')),
                ('hints', models.TextField()),
                ('boards', models.ManyToManyField(to='exam.boardyear')),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='exam.chapter')),
                ('created_by', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, db_index=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(app_label)s_%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Questions',
            },
        ),
        migrations.CreateModel(
            name='QuestionPattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveBigIntegerField(default=0, help_text='Ordering Criteria.')),
                ('is_published', models.BooleanField(default=False, help_text='If false, it will be unavailable for end user!')),
                ('is_active', models.BooleanField(default=False, help_text='Toggles the global visibility of the record, if flase then it will be deleted for the user')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('number_of_questions', models.PositiveSmallIntegerField()),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='exam.chapter')),
                ('created_by', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, db_index=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(app_label)s_%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Question Patterns',
            },
        ),
        migrations.CreateModel(
            name='QuestionComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveBigIntegerField(default=0, help_text='Ordering Criteria.')),
                ('is_published', models.BooleanField(default=False, help_text='If false, it will be unavailable for end user!')),
                ('is_active', models.BooleanField(default=False, help_text='Toggles the global visibility of the record, if flase then it will be deleted for the user')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('comment', models.TextField()),
                ('created_by', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='exam.question')),
                ('updated_by', models.ForeignKey(blank=True, db_index=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(app_label)s_%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Question Comments',
            },
        ),
        migrations.CreateModel(
            name='QuestionAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveBigIntegerField(default=0, help_text='Ordering Criteria.')),
                ('is_published', models.BooleanField(default=False, help_text='If false, it will be unavailable for end user!')),
                ('is_active', models.BooleanField(default=False, help_text='Toggles the global visibility of the record, if flase then it will be deleted for the user')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='exam.answer')),
                ('created_by', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='exam.question')),
                ('updated_by', models.ForeignKey(blank=True, db_index=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(app_label)s_%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Question Answers',
            },
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveBigIntegerField(default=0, help_text='Ordering Criteria.')),
                ('is_published', models.BooleanField(default=False, help_text='If false, it will be unavailable for end user!')),
                ('is_active', models.BooleanField(default=False, help_text='Toggles the global visibility of the record, if flase then it will be deleted for the user')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('number_of_questions', models.PositiveSmallIntegerField()),
                ('exam_cost', models.FloatField()),
                ('exam_procedure', models.TextField()),
                ('created_by', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('exam_title', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='exam.examtitle')),
                ('question_patterns', models.ManyToManyField(to='exam.questionpattern')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='exam.subject')),
                ('updated_by', models.ForeignKey(blank=True, db_index=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(app_label)s_%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Exams',
            },
        ),
    ]
