# Generated by Django 4.0.5 on 2022-06-25 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0010_answer_question_questionpattern_questioncomment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='image',
            field=models.ImageField(upload_to='media/question/images/'),
        ),
    ]
