# Generated by Django 4.0.5 on 2022-06-27 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0010_answer_question_questionpattern_questioncomment_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'ordering': ('sequence', 'created_at'), 'verbose_name': 'Answere', 'verbose_name_plural': '6.1. Answeres'},
        ),
        migrations.AlterModelOptions(
            name='boardyear',
            options={'ordering': ('sequence', 'code', 'created_at'), 'verbose_name': 'Board', 'verbose_name_plural': '4. Boards'},
        ),
        migrations.AlterModelOptions(
            name='chapter',
            options={'ordering': ('sequence', 'created_at'), 'verbose_name': 'Chapter', 'verbose_name_plural': '3.2. Chapters'},
        ),
        migrations.AlterModelOptions(
            name='chaptercategory',
            options={'ordering': ('sequence', 'created_at'), 'verbose_name': 'Chapter Category', 'verbose_name_plural': '3.1. Chapter Categories'},
        ),
        migrations.AlterModelOptions(
            name='exam',
            options={'ordering': ('sequence', 'created_at'), 'verbose_name': 'Exam', 'verbose_name_plural': '7. Exams'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ('sequence', 'created_at'), 'verbose_name': 'Question', 'verbose_name_plural': '5.1. Questions'},
        ),
        migrations.AlterModelOptions(
            name='questionanswer',
            options={'ordering': ('sequence', 'created_at'), 'verbose_name': 'Question Answer', 'verbose_name_plural': '6.2. Question Answers'},
        ),
        migrations.AlterModelOptions(
            name='questioncomment',
            options={'ordering': ('sequence', 'created_at'), 'verbose_name': 'Question Comment', 'verbose_name_plural': '5.2. Question Comment'},
        ),
        migrations.AlterModelOptions(
            name='questionpattern',
            options={'ordering': ('sequence', 'created_at'), 'verbose_name': 'Question Pattern', 'verbose_name_plural': '6.3. Question Patterns'},
        ),
        migrations.AlterModelOptions(
            name='subject',
            options={'ordering': ('sequence', 'created_at'), 'verbose_name': 'Subject', 'verbose_name_plural': '2.2. Subjects'},
        ),
        migrations.AlterModelOptions(
            name='subjectcategory',
            options={'ordering': ('sequence', 'created_at'), 'verbose_name': 'Subject Category', 'verbose_name_plural': '2.1. Subject Categories'},
        ),
        migrations.AlterField(
            model_name='question',
            name='image',
            field=models.ImageField(upload_to='media/question/images/'),
        ),
        migrations.AlterModelTable(
            name='answer',
            table='answere',
        ),
        migrations.AlterModelTable(
            name='exam',
            table='exam',
        ),
        migrations.AlterModelTable(
            name='question',
            table='question',
        ),
        migrations.AlterModelTable(
            name='questionanswer',
            table='question_answer',
        ),
        migrations.AlterModelTable(
            name='questioncomment',
            table='question_comment',
        ),
        migrations.AlterModelTable(
            name='questionpattern',
            table='question_pattern',
        ),
    ]
