# Generated by Django 4.0.5 on 2022-07-03 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0011_alter_answer_options_alter_boardyear_options_and_more'),
        ('exam', '0011_alter_question_image'),
    ]

    operations = [
    ]
