# Generated by Django 4.0.5 on 2022-06-25 14:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0010_answer_question_questionpattern_questioncomment_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('exam_history', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveBigIntegerField(default=0, help_text='Ordering Criteria.')),
                ('is_published', models.BooleanField(default=False, help_text='If false, it will be unavailable for end user!')),
                ('is_active', models.BooleanField(default=False, help_text='Toggles the global visibility of the record, if flase then it will be deleted for the user')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('exam_reference', models.URLField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('total_marks', models.CharField(max_length=50)),
                ('total_correct_answers', models.PositiveSmallIntegerField()),
                ('total_number_unanswersed', models.PositiveSmallIntegerField()),
                ('total_wrong_answers', models.PositiveSmallIntegerField()),
                ('earned_points', models.PositiveSmallIntegerField()),
                ('created_by', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(app_label)s_%(class)s_created_by', to=settings.AUTH_USER_MODEL)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='exam.exam')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='exam.subject')),
                ('updated_by', models.ForeignKey(blank=True, db_index=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='%(app_label)s_%(class)s_updated_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Exam Histories',
            },
        ),
    ]
