# Generated by Django 4.0.5 on 2022-07-04 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam_history', '0002_examhistory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favoriteexam',
            options={'verbose_name_plural': 'Favorite Exams'},
        ),
    ]
